export default {
// COLORS
  COLOR_WHITE: '#fff',
  COLOR_DIRTY_WHITE: '#f4f4f4',
  COLOR_LIGHT_BLUE: '#00cfff',
  COLOR_MEDIUM_BLUE: '#008bff',
  COLOR_BLUE: '#0079ff',
  COLOR_GRAY_HEAVY: '#7e90a5',
  COLOR_GRAY_MEDIUM: '#9fbbdb',
  COLOR_GRAY_LIGHT: '#e7e7e7',
  COLOR_GRAY_CHAT: '#e1e1e5',
  COLOR_PINK: '#ff007e',
  COLOR_BLACK: '#000',
  COLOR_LABEL: '#353a60',
  COLOR_NORMAL_FONT: '#5f5f5f',
  COLOR_SIGNUP_FONT: '#b5b5b5',
  COLOR_ALARM: '#ff3333',
// FONTS
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_LARGE: 25,
  FONT_SIZE_XLARGE: 35,

// CONTAINERS
  CONTAINER_PADDING: 20,

// PAGES PADDING:
  PAGE_PADDING_HORIZONTAL: 15,

// CARD RADIUS
  PAGE_CARD_RADIUS: 15,
};
