
// AUTHENTICATION TYPES
export const AUTH = {

  REGISTER: {
    REQUEST: 'AUTH_REGISTER_REQUEST',
    SUCCESS: 'AUTH_REGISTER_SUCCESS',
    FAILED: 'AUTH_REGISTER_FAILED',
  },

  LOGIN: {
    REQUEST: 'AUTH_LOGIN_REQUEST',
    SUCCESS: 'AUTH_LOGIN_SUCCESS',
    FAILED: 'AUTH_LOGIN_FAILED'
  }

};

export const USER = {
  GET: {
    PROFILE: {
      REQUEST: 'USER_GET_PROFILE_REQUEST',
      SUCCESS: 'USER_GET_PROFILE_SUCCESS',
      FAILED: 'USER_GET_PROFILE_FAILED'
    },
    TOKEN: 'USER_GET_TOKEN'
  }
};

export const COUNTER = {
  INCREASE: 'INCREASE_COUNTER',
  DECREASE: 'DECREASE_COUNTER'
};
