// AUTHENTICATION TYPES
export const AUTH = {
  REGISTER: {
    REQUEST: 'AUTH_REGISTER_REQUEST',
    SUCCESS: 'AUTH_REGISTER_SUCCESS',
    FAILED: 'AUTH_REGISTER_FAILED',
  },
  LOGIN: {
    REQUEST: 'AUTH_LOGIN_REQUEST',
    SUCCESS: 'AUTH_LOGIN_SUCCESS',
    FAILED: 'AUTH_LOGIN_FAILED',
  }
};

export const USER = {
  GET: {
    PROFILE: {
      REQUEST: 'USER_GET_PROFILE_REQUEST',
      SUCCESS: 'USER_GET_PROFILE_SUCCESS',
      FAILED: 'USER_GET_PROFILE_FAILED',
    },
    TOKEN: 'USER_GET_TOKEN',
  },
  UPDATE: {
    NOTIFICATION: 'USER_NOTIFICATION_UPDATE'
  }
};

export const CAMPAIGN = {
  SELECTED: 'CAMPAIGN_SELECTED',
  LIST: {
    CHANGE: 'CAMPAIGN_CHANGE_REQUEST',
    REQUEST: 'CAMPAIGN_GET_REQUEST',
    SUCCESS: 'CAMPAIGN_GET_SUCCESS',
    FAILED: 'CAMPAIGN_GET_FAILED',
  },
  RECOMMENDED: {
    REQUEST: 'CAMPAIGN_RECOMMENDED_REQUEST',
    SUCCESS: 'CAMPAIGN_RECOMMENDED_SUCCESS',
    FAILED: 'CAMPAIGN_RECOMMENDED_FAILED',
  },
  MYLIST: {
    GET: 'CAMPAIGN_MYLIST_GET',
    UPDATE: 'CAMPAIGN_MYLIST_UPDATE',
    ADD: 'CAMPAIGN_MYLIST_ADD',
    SELECTED: 'CAMPAIGN_MYLIST_SELECTED',
  },
  TRIP: {
    START: 'CAMPAIGN_TRIP_START',
    END: 'CAMPAIGN_TRIP_END',
  },
  FAVORITE: {
    REQUEST: 'CAMPAIGN_FAVORITE_REQUEST',
    SUCCESS: 'CAMPAIGN_FAVORITE_SUCCESS',
    FAILED: 'CAMPAIGN_FAVORITE_FAILED'
  },
  RESET: 'CAMPAIGN_RESET',
  LOCATION: {
    REQUEST: 'CAMPAIGN_LOCATION_REQUEST',
    SUCCESS: 'CAMPAIGN_LOCATION_SUCCESS',
    FAILED: 'CAMPAIGN_LOCATION_FAILED'
  }
};
