// AUTHENTICATION TYPES
export const AUTH = {
  REGISTER: {
    REQUEST: 'AUTH_REGISTER_REQUEST',
    SUCCESS: 'AUTH_REGISTER_SUCCESS',
    FAILED: 'AUTH_REGISTER_FAILED',
  },
  LOGIN: {
    REQUEST: 'AUTH_LOGIN_REQUEST',
    SUCCESS: 'AUTH_LOGIN_SUCCESS',
    FAILED: 'AUTH_LOGIN_FAILED',
  }
};

export const USER = {
  GET: {
    PROFILE: {
      REQUEST: 'USER_GET_PROFILE_REQUEST',
      SUCCESS: 'USER_GET_PROFILE_SUCCESS',
      FAILED: 'USER_GET_PROFILE_FAILED',
    },
    TOKEN: 'USER_GET_TOKEN',
  },
  NOTIFICATION: {
    SUCCESS: 'USER_NOTIFICATION_SUCCESS',
    FAILED: 'USER_NOTIFICATION_FAILED',
    UPDATE: 'USER_NOTIFICATION_UPDATE',
    GET: 'USER_NOTIFICATION_GET'
  },
  VEHICLE: {
    NEW: 'USER_VEHICLE_NEW'
  }
};

export const CAMPAIGN = {
  SELECTED: 'CAMPAIGN_SELECTED',
  LIST: {
    CHANGE: 'CAMPAIGN_CHANGE_REQUEST',
    REQUEST: 'CAMPAIGN_GET_REQUEST',
    SUCCESS: 'CAMPAIGN_GET_SUCCESS',
    FAILED: 'CAMPAIGN_GET_FAILED',
  },
  RECOMMENDED: {
    REQUEST: 'CAMPAIGN_RECOMMENDED_REQUEST',
    SUCCESS: 'CAMPAIGN_RECOMMENDED_SUCCESS',
    FAILED: 'CAMPAIGN_RECOMMENDED_FAILED',
  },
  MYLIST: {
    REQUEST: 'CAMPAIGN_MYLIST_REQUEST',
    GET: 'CAMPAIGN_MYLIST_GET',
    UPDATE: 'CAMPAIGN_MYLIST_UPDATE',
    ADD: 'CAMPAIGN_MYLIST_ADD',
    SELECTED: 'CAMPAIGN_MYLIST_SELECTED'
  },
  TRIP: {
    START: 'CAMPAIGN_TRIP_START',
    END: 'CAMPAIGN_TRIP_END',
  },
  FAVORITE: {
    REQUEST: 'CAMPAIGN_FAVORITE_REQUEST',
    SUCCESS: 'CAMPAIGN_FAVORITE_SUCCESS',
    FAILED: 'CAMPAIGN_FAVORITE_FAILED'
  },
  RESET: 'CAMPAIGN_RESET',
  LOCATION: {
    REQUEST: 'CAMPAIGN_LOCATION_REQUEST',
    SUCCESS: 'CAMPAIGN_LOCATION_SUCCESS',
    FAILED: 'CAMPAIGN_LOCATION_FAILED'
  },
  VEHICLE_MONTHLY_UPDATE: 'CAMPAIGN_VEHICLE_MONTHLY_UPDATE'
};

export const SIGNUP = {
  INFO: 'SIGNUP_INFO_DATA',
  IMAGES: 'SIGNUP_IMAGES_DATA',
  RESET: 'SIGNUP_DATA_RESET'
};